# Generated by Django 2.2 on 2020-12-21 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed'), ('drawn', 'Drawn')], default='pending', max_length=50)),
                ('weight_class', models.CharField(blank=True, default='', max_length=50)),
                ('method', models.CharField(blank=True, default='', max_length=100)),
                ('round', models.IntegerField(blank=True, default=1)),
                ('time', models.TimeField()),
                ('detail_link', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('date', models.DateField()),
                ('status', models.CharField(blank=True, choices=[('upcoming', 'Upcoming'), ('completed', 'Completed')], default='upcoming', max_length=50)),
                ('detail_link', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('finished', models.BooleanField(blank=True, default=False, null=True)),
                ('bout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bouts', to='contest.Bout')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_events', to='contest.Event')),
                ('fighter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fighters', to='contest.Fighter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bout',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bout_events', to='contest.Event'),
        ),
        migrations.AddField(
            model_name='bout',
            name='fighter1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fighter1s', to='contest.Fighter'),
        ),
        migrations.AddField(
            model_name='bout',
            name='fighter2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fighter2s', to='contest.Fighter'),
        ),
        migrations.AddField(
            model_name='bout',
            name='loser',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='losers', to='contest.Fighter'),
        ),
        migrations.AddField(
            model_name='bout',
            name='winner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='contest.Fighter'),
        ),
    ]
