# Generated by Django 2.2 on 2020-12-16 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20201216_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bout',
            name='fighter1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fighter1', to='contest.Fighter'),
        ),
    ]
