# Generated by Django 2.2 on 2020-12-16 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_auto_20201216_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='bout',
            name='fighter2',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='fighter2', to='contest.Fighter'),
        ),
    ]
