# Generated by Django 2.2 on 2020-12-16 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_bout_fighter2'),
    ]

    operations = [
        migrations.AddField(
            model_name='bout',
            name='detail_link',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='bout',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='contest.Event'),
        ),
        migrations.AddField(
            model_name='bout',
            name='loser',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='loser', to='contest.Fighter'),
        ),
        migrations.AddField(
            model_name='bout',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='bout',
            name='weight_class',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bout',
            name='winner',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='contest.Fighter'),
        ),
    ]
