# Generated by Django 2.2 on 2021-01-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_auto_20210114_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bout',
            name='detail_link',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
