# Generated by Django 2.2 on 2021-01-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_auto_20210114_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='started',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
