# Generated by Django 2.2 on 2020-12-16 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_auto_20201216_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bout',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='contest.Event'),
        ),
    ]
