# Generated by Django 2.2 on 2021-01-14 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_event_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bout',
            name='round',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
