# Generated by Django 2.2 on 2020-12-16 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0007_auto_20201216_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bout',
            name='fighter2',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fighter2', to='contest.Fighter'),
        ),
    ]
