# Generated by Django 2.2 on 2021-01-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0007_auto_20210114_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bout',
            name='round',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
