# Generated by Django 2.2 on 2021-01-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_auto_20210115_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='started',
        ),
        migrations.AddField(
            model_name='event',
            name='action',
            field=models.CharField(blank=True, choices=[('unknown', 'Unknown'), ('started', 'Started'), ('completed', 'Completed')], default='---', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(blank=True, choices=[('upcoming', 'Upcoming'), ('old', 'Old')], default='upcoming', max_length=50),
        ),
    ]
