# Generated by Django 2.2 on 2020-12-16 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_auto_20201216_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bout',
            name='loser',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='loser', to='contest.Fighter'),
        ),
        migrations.AlterField(
            model_name='bout',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed'), ('drawn', 'Drawn')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='bout',
            name='winner',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='contest.Fighter'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(blank=True, choices=[('upcoming', 'Upcoming'), ('complete', 'Completed')], default='upcoming', max_length=50),
        ),
    ]
