# Generated by Django 2.2 on 2021-01-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0009_auto_20210115_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='action',
            field=models.CharField(blank=True, choices=[('started', 'Started'), ('completed', 'Completed')], max_length=50),
        ),
    ]
