# Generated by Django 2.2 on 2020-12-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0010_auto_20201216_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
