# Generated by Django 3.1 on 2021-01-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0012_auto_20210122_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
