# Generated by Django 2.2 on 2020-12-17 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0013_auto_20201216_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bout',
            name='loser',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='loser', to='contest.Fighter'),
        ),
        migrations.AlterField(
            model_name='bout',
            name='winner',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='contest.Fighter'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(blank=True, choices=[('upcoming', 'Upcoming'), ('completed', 'Completed')], default='upcoming', max_length=50),
        ),
    ]
