# Generated by Django 2.2 on 2020-12-18 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0015_auto_20201217_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bout',
            name='fighter1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fighter1', to='contest.Fighter'),
        ),
        migrations.AlterField(
            model_name='bout',
            name='fighter2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fighter2', to='contest.Fighter'),
        ),
        migrations.AlterField(
            model_name='bout',
            name='loser',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loser', to='contest.Fighter'),
        ),
        migrations.AlterField(
            model_name='bout',
            name='winner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='contest.Fighter'),
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('finished', models.BooleanField(blank=True, default=False, null=True)),
                ('bout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bout', to='contest.Bout')),
                ('fighter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fighter', to='contest.Fighter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
