# Generated by Django 2.2 on 2020-12-19 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0016_auto_20201218_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entry_events', to='contest.Event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bout',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bout_events', to='contest.Event'),
        ),
        migrations.AlterField(
            model_name='bout',
            name='fighter1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fighter1s', to='contest.Fighter'),
        ),
        migrations.AlterField(
            model_name='bout',
            name='fighter2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fighter2s', to='contest.Fighter'),
        ),
        migrations.AlterField(
            model_name='bout',
            name='loser',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='losers', to='contest.Fighter'),
        ),
        migrations.AlterField(
            model_name='bout',
            name='winner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='contest.Fighter'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='bout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bouts', to='contest.Bout'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='fighter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fighters', to='contest.Fighter'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
