# Generated by Django 3.1 on 2021-02-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0016_auto_20210205_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='rank',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
