# Generated by Django 2.2 on 2020-12-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0017_auto_20201219_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='bout',
            name='method',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bout',
            name='round',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='bout',
            name='time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
