# Generated by Django 3.1 on 2021-02-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0018_auto_20210205_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fq_points',
            field=models.PositiveIntegerField(blank=True, default=100, null=True),
        ),
    ]
