# Generated by Django 3.1 on 2021-02-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0019_customuser_fq_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='ranking',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
