# Generated by Django 2.2 on 2020-12-29 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0020_auto_20201222_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='bout',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='fighter',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='finished',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='status',
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bouts', to='contest.Bout')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='contest.Entry')),
                ('fighter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fighters', to='contest.Fighter')),
            ],
        ),
    ]
