# Generated by Django 3.1 on 2021-02-12 21:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0020_auto_20210205_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='displayname',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_registration', models.CharField(blank=True, choices=[('private', 'Private'), ('public', 'Public')], default='public', max_length=50)),
                ('instructions', models.TextField(blank=True, default='', max_length=50)),
                ('rules_set', models.TextField(blank=True, default='', max_length=50)),
                ('date_started', models.DateTimeField(blank=True, null=True)),
                ('entrants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_event', to='contest.event')),
            ],
        ),
    ]
