# Generated by Django 2.2 on 2021-01-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0021_auto_20201229_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='bout',
            name='go_the_distance',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
