# Generated by Django 3.1 on 2021-02-15 16:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0021_auto_20210212_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='entrants',
            field=models.ManyToManyField(blank=True, related_name='game_entrants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='instructions',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='game',
            name='rules_set',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
