# Generated by Django 3.1 on 2021-02-17 14:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0022_auto_20210215_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='joind_users',
            field=models.ManyToManyField(blank=True, related_name='game_joined_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
