# Generated by Django 3.1 on 2021-02-22 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0022_auto_20210222_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='game',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_games', to='contest.game'),
        ),
    ]
