# Generated by Django 3.1 on 2021-02-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0023_auto_20210222_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
