# Generated by Django 2.2 on 2021-01-04 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0023_auto_20210104_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selection',
            name='fighter',
        ),
        migrations.AddField(
            model_name='selection',
            name='survivor1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survivor1s', to='contest.Fighter'),
        ),
        migrations.AddField(
            model_name='selection',
            name='survivor2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survivor2s', to='contest.Fighter'),
        ),
        migrations.AlterField(
            model_name='bout',
            name='go_the_distance',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
