# Generated by Django 3.1 on 2021-02-17 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0023_game_joind_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='joind_users',
            new_name='joined_users',
        ),
    ]
