# Generated by Django 3.1 on 2021-02-17 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0024_auto_20210217_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='game',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='contest.game'),
        ),
    ]
