# Generated by Django 2.2 on 2021-01-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0024_auto_20210104_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='last_edited',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
