# Generated by Django 3.1 on 2021-02-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0025_entry_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='instructions',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='game',
            name='rules_set',
            field=models.TextField(default='', max_length=500),
        ),
    ]
