# Generated by Django 3.1 on 2021-02-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0026_auto_20210219_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='action',
            field=models.CharField(blank=True, choices=[('started', 'Started'), ('completed', 'Completed')], max_length=50),
        ),
    ]
