# Generated by Django 3.1 on 2021-03-02 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0026_auto_20210226_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='date',
        ),
    ]
