# Generated by Django 3.1 on 2021-02-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0027_game_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='action',
            field=models.CharField(blank=True, choices=[('started', 'Started'), ('completed', 'Completed')], default='started', max_length=50),
        ),
    ]
