# Generated by Django 3.1 on 2021-02-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0028_auto_20210219_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date_started',
            field=models.DateTimeField(null=True),
        ),
    ]
