# Generated by Django 3.1 on 2021-03-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0028_remove_game_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='buyin',
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='buyin_bonus',
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(blank=True, choices=[('free', 'Free'), ('paid', 'Paid')], default='free', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fq_points',
            field=models.PositiveIntegerField(blank=True, default=1000, null=True),
        ),
    ]
