# Generated by Django 3.1 on 2021-03-04 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0029_auto_20210304_0115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='fq_points',
            new_name='coins',
        ),
    ]
