# Generated by Django 3.1 on 2021-03-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0031_auto_20210304_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='instructions',
            field=models.TextField(default='Choose fighters\nHope they all survive', max_length=500),
        ),
        migrations.AlterField(
            model_name='game',
            name='rules_set',
            field=models.TextField(default='User can pick any number of fighters. If any of them get finished, user is eliminated.\nOut of all surviving entries, the user with the most surviving fighters, wins the contest.\nIf there is a tie, the winner is the entry with the most winning fighters.\nYou are allowed to resubmit your team. 1 team per person.', max_length=500),
        ),
    ]
