# Generated by Django 3.1 on 2021-03-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0037_auto_20210315_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='entry_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
