# Generated by Django 3.1 on 2021-03-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0037_auto_20210315_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='gender',
            field=models.CharField(blank=True, default='M', max_length=10),
        ),
    ]
