# Generated by Django 3.1 on 2021-03-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0038_game_entry_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='entry_number',
        ),
        migrations.AddField(
            model_name='entry',
            name='retry_number',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='retry_times',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
