# Generated by Django 3.1 on 2021-03-19 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0038_fighter_gender'),
        ('contest', '0039_auto_20210316_0656'),
    ]

    operations = [
    ]
