# Generated by Django 3.1 on 2021-03-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0040_merge_20210319_0157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='retry_times',
            new_name='multientry',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='retry_number',
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_number',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Used in tournament type game. The user can re-sumbit entry up to this number of times', null=True),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10),
        ),
    ]
