# Generated by Django 3.1 on 2021-03-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0042_auto_20210324_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='added_prizepool',
            field=models.PositiveIntegerField(blank=True, default=100, null=True),
        ),
    ]
